name: Events Demo 1
on:
  pull_request:
    types: #opened #[opened, edited] #either single, or with brackers OR with a list
      - opened
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3

      - name: Install PNPM
        run: |
          npm install --global corepack@latest
          corepack enable pnpm

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Test code
        run: pnpm run test
      - name: Build code
        run: pnpm run build
      - name: Deploy project
        run: echo "Deploying..."
