name: Check app

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6

      - name: Install NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install PNPM
        run: |
          npm install --global corepack@latest
          corepack enable pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: test
        run: pnpm test

      - name: build
        run: pnpm build

      - name: Deploy code
        run: echo "Deploying..."
